CREATE DATABASE IF NOT EXISTS PROJETO1BD;
USE PROJETO1BD;


CREATE TABLE CARGO (
    cod_cargo INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(50) NOT NULL,
    descricao VARCHAR(200)
);


CREATE TABLE ORGAO_PUBLICO (
    cod_orgao INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    estado VARCHAR(18) NOT NULL,
    descr VARCHAR(200),
    data_ini DATE NOT NULL,
    data_fim DATE
);


CREATE TABLE FUNCIONARIO (
    cod_func INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    orgao_pub INT NOT NULL,
    cargo INT NOT NULL,
    cpf VARCHAR(11) NOT NULL,
    data_nasc DATE NOT NULL,
    inicio_contrato DATE NOT NULL,
    fim_contrato DATE,
    FOREIGN KEY (orgao_pub) REFERENCES ORGAO_PUBLICO(cod_orgao)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (cargo) REFERENCES CARGO(cod_cargo)
        ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE LOCALIDADE (
    cod_local INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    estado VARCHAR(30) NOT NULL,
    municipio VARCHAR(100) NOT NULL,
    bairro VARCHAR(100) NOT NULL,
    endereco VARCHAR(200) NOT NULL
);


CREATE TABLE MORADOR (
    cod_morador INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    endereco INT NOT NULL,
    cpf VARCHAR(11) NOT NULL,
    data_nasc DATE NOT NULL,
    FOREIGN KEY (endereco) REFERENCES LOCALIDADE(cod_local)
        ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE EMAIL (
    cod_email INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    cod_func INT,
    cod_morador INT,
    email VARCHAR(200),
    FOREIGN KEY (cod_func) REFERENCES FUNCIONARIO(cod_func)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (cod_morador) REFERENCES MORADOR(cod_morador)
        ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE TELEFONE (
    telefone VARCHAR(9) NOT NULL PRIMARY KEY,
    cod_morador INT,
    DDD VARCHAR(2),
    FOREIGN KEY (cod_morador) REFERENCES MORADOR(cod_morador)
        ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE TIPO_OCORRENCIA (
    cod_tipo INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    orgao_pub INT NOT NULL,
    nome VARCHAR(100) NOT NULL,
    descr VARCHAR(200),
    FOREIGN KEY (orgao_pub) REFERENCES ORGAO_PUBLICO(cod_orgao)
        ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE OCORRENCIA (
    cod_oco INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    cod_tipo INT NOT NULL,
    cod_local INT NOT NULL,
    cod_morador INT NOT NULL,
    data DATE NOT NULL,
    status VARCHAR(10) NOT NULL,
    FOREIGN KEY (cod_tipo) REFERENCES TIPO_OCORRENCIA(cod_tipo)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (cod_local) REFERENCES LOCALIDADE(cod_local)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (cod_morador) REFERENCES MORADOR(cod_morador)
        ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE SERVICO (
    cod_servico INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    cod_orgao INT NOT NULL,
    cod_local INT NOT NULL,
    nome VARCHAR(100) NOT NULL,
    descr VARCHAR(200),
    inicio_servico DATE,
    fim_servico DATE,
    FOREIGN KEY (cod_orgao) REFERENCES ORGAO_PUBLICO(cod_orgao)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (cod_local) REFERENCES LOCALIDADE(cod_local)
        ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE AVALIACAO (
    cod_aval INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    cod_servico INT NOT NULL,
    cod_morador INT NOT NULL,
    nota_serv INT NOT NULL,
    nota_tempo INT NOT NULL,
    opiniao VARCHAR(200),
    FOREIGN KEY (cod_servico) REFERENCES SERVICO(cod_servico)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (cod_morador) REFERENCES MORADOR(cod_morador)
        ON DELETE CASCADE ON UPDATE CASCADE
);
